name: Java CI with Maven

on:
  push:
    branches: [ master ]
    paths-ignore:
      - "**.md"

  schedule:
    - cron: '0 4 * * 1-5'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - run: cp env/env.sample .env

    - name: Build with Maven
      run: mvn clean install

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v2.10.0
      with:
          push: true
          tags: dikabrenda/maven_project:latest
